[versions]
apacheDS = "2.0.0.AM27"
assertj = "3.27.7"
commonsValidator = "1.10.1"
gradleOci-junitJupiter = "0.8.0"
hivemq-extensionSdk = "4.1.0"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "5.10.0"
logback = "1.5.31"
mockito = "5.21.0"
netty = "4.2.10.Final"
owner = "1.0.12"
testcontainers = "2.0.3"

[libraries]
apacheDS-dns = { module = "org.apache.directory.server:apacheds-protocol-dns", version.ref = "apacheDS" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commonsValidator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
netty-resolver-dns = { module = "io.netty:netty-resolver-dns", version.ref = "netty" }
owner = { module = "org.aeonbits.owner:owner", version.ref = "owner" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq", version.ref = "testcontainers" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
